# Generated by Django 2.1.7 on 2019-04-09 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppl_joinus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joinusevent',
            options={'verbose_name': 'Joinus Event'},
        ),
        migrations.AlterModelOptions(
            name='joinusformpage',
            options={'verbose_name': 'Joinus Form Builder'},
        ),
    ]
