# Generated by Django 4.2.1 on 2023-10-24 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('ppl_joinus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinusevent',
            name='success_page',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_success', to='wagtailcore.page'),
        ),
    ]
