# Generated by Django 4.2.1 on 2023-09-10 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppl_joinus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinusevent',
            name='notify_email',
            field=models.EmailField(blank='true', max_length=254, null=True, verbose_name='Notify Admin Email'),
        ),
    ]
