# Generated by Django 4.2.1 on 2023-09-14 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppl_joinus', '0002_alter_joinusevent_notify_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinusregistration',
            name='cancelled',
        ),
    ]
