# Generated by Django 4.2.1 on 2023-09-14 23:09

from django.db import migrations, models
import ppl_joinus.models


class Migration(migrations.Migration):

    dependencies = [
        ('ppl_joinus', '0003_remove_joinusregistration_cancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinusformfield',
            name='label',
            field=models.CharField(help_text='The label of the form field, cannot be one of the following: Your Name, Email.', max_length=255, validators=[ppl_joinus.models.validate_label], verbose_name='label'),
        ),
    ]
