# Generated by Django 4.2.1 on 2023-09-22 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppl_joinus', '0004_alter_joinusformfield_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinusevent',
            name='notify_email',
        ),
    ]
