# Generated by Django 2.2.9 on 2020-02-13 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppl_joinus', '0005_auto_20190410_1543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joinususerformbuilder',
            options={'verbose_name': 'form submission', 'verbose_name_plural': 'form submissions'},
        ),
    ]
