# Generated by Django 2.2.9 on 2020-02-14 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppl_joinus', '0006_auto_20200212_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinusevent',
            name='registration_form_chooser',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ppl_joinus.JoinusFormPage'),
        ),
        migrations.AlterField(
            model_name='joinusevent',
            name='success_page',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ppl_joinus.SuccessPage'),
        ),
    ]
