# Generated by Django 2.2.9 on 2020-02-14 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppl_joinus', '0007_auto_20200213_1701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joinusregistration',
            options={'verbose_name': 'Event Registration'},
        ),
    ]
