# Generated by Django 2.2.9 on 2020-03-13 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppl_joinus', '0009_auto_20200311_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinusregistration',
            name='cancelled',
            field=models.BooleanField(default=0),
        ),
    ]
