# Generated by Django 2.2.9 on 2020-04-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppl_joinus', '0010_joinusregistration_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinusevent',
            name='from_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='joinusevent',
            name='success_message',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
