# Generated by Django 2.2.9 on 2020-04-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppl_joinus', '0012_auto_20200417_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinusevent',
            name='success_email_sub',
            field=models.CharField(default='You have been registered for', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='joinusevent',
            name='waitlist_email_msg',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='joinusevent',
            name='waitlist_email_sub',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
