# Generated by Django 2.2.9 on 2020-04-17 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppl_joinus', '0013_auto_20200417_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinusevent',
            name='success_email_sub',
        ),
        migrations.RemoveField(
            model_name='joinusevent',
            name='waitlist_email_sub',
        ),
    ]
