# Generated by Django 2.2.9 on 2020-04-17 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppl_joinus', '0014_auto_20200417_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinusevent',
            name='notify_email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Sends a notification that a user has registered'),
        ),
        migrations.AlterField(
            model_name='joinusevent',
            name='success_email_msg',
            field=models.CharField(max_length=2000, null=True, verbose_name='Body of the success email'),
        ),
        migrations.AlterField(
            model_name='joinusevent',
            name='waitlist_email_msg',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Body of the waitlist email'),
        ),
    ]
