# Generated by Django 2.2.9 on 2020-04-17 23:29

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ppl_joinus', '0015_auto_20200417_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinusevent',
            name='notify_email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Notify Admin Email'),
        ),
        migrations.AlterField(
            model_name='joinusevent',
            name='success_email_msg',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Body of the success email'),
        ),
    ]
