# Generated by Django 2.2.9 on 2020-04-17 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppl_joinus', '0016_auto_20200417_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinusevent',
            name='from_email',
        ),
    ]
